name: myworkspace
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  convex_bottom_bar: ^3.2.0
  syncfusion_flutter_calendar: ^28.1.33

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  assets:
    - assets/images/logo/logorewise.png
    # - assets/logorewises.png
    - assets/images/logo/prads.png
    - assets/images/logo/logocolor.svg
    - assets/images/logo/logocolors.svg
    - assets/images/logo/logonoir.svg
    - assets/images/logo/logoblanc.svg
    # - assets/images/logo/img1.svg
    - assets/images/logo/img2.png
    - assets/images/autres/aa.png
    - assets/images/autres/succes.png
    - assets/images/autres/error.png
    - assets/images/logo/pradi.svg
    # - assets/images/sbar/actions.svg
    - assets/images/sbar/crm.svg
    - assets/images/sbar/actions.svg
    - assets/images/sbar/fixit.svg
    - assets/images/sbar/hr.svg
    - assets/images/sbar/incident.svg
    - assets/images/sbar/journey.svg
    - assets/images/sbar/meeting.svg
    - assets/images/sbar/workspace.svg
    - assets/images/sbar/procu.svg
    - assets/images/sbar/prosync.svg
    - assets/images/sbar/sop.svg
    - assets/images/autres/aa.png
    - assets/images/sbar/chart-account.svg
    - assets/images/sbar/bud.svg
    - assets/images/sbar/work-permit.svg
    
    - assets/fonts/
  fonts:
    - family: Suse
      fonts:
        - asset: assets/fonts/suse/SUSE-Regular.ttf
        - asset: assets/fonts/suse/SUSE-Bold.ttf
        - asset: assets/fonts/suse/SUSE-Light.ttf
        - asset: assets/fonts/suse/SUSE-SemiBold.ttf
        - asset: assets/fonts/suse/SUSE-Medium.ttf
        - asset: assets/fonts/suse/SUSE-ExtraLight.ttf
        - asset: assets/fonts/suse/SUSE-Medium.ttf
        - asset: assets/fonts/suse/SUSE-Medium.ttf
    - family: BBigerOver
      fonts:
        - asset: assets/fonts/bBigerOver/bBigerOver.ttf
       

  uses-material-design: true
  generate: true

  
